name: flame_camera_practice
description: "A new Flutter project."
publish_to: 'none' 

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame_camera_tools: ^2.0.0
  flame: ^1.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
